name: "[Bug] Something bad happened"
description: "Point it in the doll."
title: "[Bug] Describe your sad issues"
labels:
- wontfix
- bug
assignees:
- "jpedro"

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking _your_ time to fill out this **bug report**.

- type: textarea
  id: description
  validations:
    required: true
  attributes:
    label: Description
    description: |
      Give us a brief description of what happened and what
      should have happened.

- type: textarea
  id: steps
  validations:
    required: false
  attributes:
    label: Steps
    description: |
      Steps to reproduce the behavior.
    placeholder: |
      1. Go to google.com.
      2. Enter "zero fucks given".
      3. See the problem in plain day light.

# - type: textarea
#   id: additional
#   attributes:
#     label: Additional
#     description: |
#       Provide any additional information such as logs, screenshots,
#       scenarios in which the bug occurs so that it facilitates
#       resolving the issue.
