name: Go

on:
  workflow_call:
    inputs:
      exampleDir:
        type: string
        description: Does this repo has an "example" to run? If so where?

      envFile:
        type: string
        description: Loads a `env` file

      testPath:
        type: string
        description: The package path to be tested
        default: "./..."

jobs:
  test:
    name: Go
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Export
      run: |
        echo "Simple export"
        export
        echo "---"

    - name: Parse
      run: |
        echo
        echo "Parse the env"
        env | while IFS= read -r line
        do
          key="${line%%=*}"
          val="${line#*=}"
          echo -e "\033[32;1m${key}\033[0m=${val}"
          echo -e "[${key:0:1} ... ${key:1}] ==> [${val:0:1} ... ${val:1}]"
          echo
        done
        echo
        echo "Done"

    - name: Load envFile
      if: inputs.envFile != ''
      run: |
        echo "==> envFile ${{ inputs.envFile }} would be loaded here."

    - name: Set up go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Run lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60

    - name: Run test
      run: |
        go test -coverprofile /tmp/coverage.out -v ${{ inputs.testPath }}
        go tool cover -func /tmp/coverage.out

    - name: Run example
      if: inputs.exampleDir != ''
      run: |
        cd ${{ inputs.exampleDir }}
        go run .

    - name: Run build
      run: |
        go build
        ls -alFh

    - name: Run install
      run: |
        echo "==> GOROOT: $(go env GOROOT)."
        echo "==> GOPATH: $(go env GOPATH)."
        go install
        ls -alFh $(go env GOPATH)/bin/
