name: Go

on:
  workflow_call:
    inputs:
      example:
        type: boolean
        description: Does this repo has an "example/" to run?
        default: false

jobs:
  test:
    name: Go
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install go
      uses: actions/setup-go@v5

    - name: Show env
      run: |
        export

    - name: Go test
      run: |
        go test -coverprofile cover.out -v ./...
        go tool cover -func cover.out
        # go test -v -covermode=count -coverprofile=coverage.out

    - name: Go example
      if: inputs.example
      run: |
        cd example
        go run .

    - name: Go install
      run: |
        go install
        ls -la $GOPATH

    - name: Show local files
      run: |
        ls -lsRF
