name: Go

on:
  workflow_call:
    inputs:
      exampleDir:
        type: string
        description: Does this repo has an "example" to run? If so where?

      envFile:
        type: string
        description: Loads a `env` file

jobs:
  test:
    name: Go
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Export
      run: |
        echo "--- Simple export ---"
        export
        echo "---"

    - name: Env
      run: |
        echo
        echo "--- Parse the env ---"
        env | while IFS= read -r line
        do
          key=${line%%=*}
          val=${line#*=}
          echo "<<< ${key} ==> ${val}"
          echo ">>> ${key:0:1} ... ${key:1} ==> ${val:0:1} ${val:1}"
          echo
        done
        echo "---"

    - name: Set up env
      if: inputs.envFile != ''
      run: |
        echo "==> envFile ${{ inputs.envFile }} would be loaded here."

    - name: Install go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Go lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60

    - name: Go test
      run: |
        go test -coverprofile coverage.out -v ./...
        go tool cover -func coverage.out

    - name: Go example
      if: inputs.exampleDir != ''
      run: |
        cd ${{ inputs.exampleDir }}
        go run .

    - name: Go install
      run: |
        echo "==> GOROOT: $GOROOT." 
        echo "==> GOPATH: $GOPATH." 
        go install -v
        ls -alFh $GOPATH

    - name: Show local files
      run: |
        ls -lsRF
